### ISSUE TITLE
(US10) - Criação da funcao de marcar como pendende ou resolvido

### ISSUE THREAD

**Issue by cwtshh** [fga-eps-mds/2023-1-Schedula-Doc#116]
## Descrição da Issue
Foi criado os botões de marcar pendência e marcar como resolvido. Também foi adicionado um badge com a contagem de notificações que não foram lidas pelo usuário.

## Tasks:
- [x] Criação do botão de pendência.
- [x] Criação do botão de resolvido.
- [x] Adição do badge com a contagem de notificações.
- [x] Atualização dos campos no banco de dados.

**Comment by IanFPFerreira** [comment]
Objetivos dessa tarefa concluídos
